### ISSUE TITLE
`—include-introns` flag error Cell Ranger 7+

### ISSUE THREAD

**Issue by samuel-marsh** [lilab-bcb/cumulus#367] opened 2022-11-08 13:35 UTC
Hi,

Ran into error this morning running cellranger_workflow on Terra specifying Cell Ranger 7.0.1.  This appears to be due to change in how Cell Ranger handles —include-introns flag.  As of Cell Ranger 7 default intron counting behavior changed and the flag changed.  Cell Ranger now requires a true/false value following the flag.  Digging through the error I got this morning it seems it was missing a true/false value following the flag in Cell Ranger command.

Seems like would just need a version check prior to running cell ranger count to decide how to supply the flag (in case users want to use older version).

If you need any more details on error message or my run please let me know and thanks again for all the work/development of this tool!

Best,
Sam

**Comment by yihming** [comment] 2023-02-08 01:42
Hi @samuel-marsh . Sorry for missing your issue. 

I think this has been covered in Cumulus workflow's later releases. You may check out its current release v2.4.0 (https://dockstore.org/workflows/github.com/lilab-bcb/cumulus/Cellranger:2.4.0?tab=info) to your Terra workspace, and see if the issue is gone.

Please let me know if the issue remains.


Sincerely,
Yiming

**Comment by yihming** [comment] 2023-03-21 22:51
I'll close this thread. Feel free to reopen it if the issue persists.

**Closed by yihming** 2023-03-21 22:51 UTC
