### ISSUE TITLE
Terra CellRanger Workflow | run_cellranger_mkfastq: strato sync: error: the following arguments are required: --backend

### ISSUE THREAD

**Issue by SXerin** [lilab-bcb/cumulus#419] opened 2024-08-29 15:30 UTC
Dear Cumulus Team,

I am a broad member, and I am trying to run the cellranger_mkfastq and cellranger_count workflow (github.com/lilab-bcb/cumulus/Cellranger:2.6.3) on Terra. I used this tutorial to import the workflow to terra: [(https://cumulus.readthedocs.io/en/stable/cumulus_import.html)]
The cellranger version I used is 7.1.0, and the docker I used is gcr.io/broad-cumulus. I kept running into: usage: strato sync [-h] --backend BACKEND [-m] [--ionice] [--profile PROFILE]
[--quiet]
source target
**strato sync: error: the following arguments are required: --backend**
Then the job will start delocalization, and at the end, it will stop with: Required file output '/cromwell_root/output_fastqs_flowcell_directory.txt' does not exist.

I am new to the coding space, so I am quite clueless at this point, but a few things that I've checked so far are: 1. The backend is specified as "GCP" in the WDL script, which I think is correct?  2. From some other posts, the Cumulus team had mentioned they no longer have write access to the gcr.io/broad-cumulus registry, so that might be an issue. I tried changing the docker registry to something else used in other workflows, but that resulted in the same error. 

Any help is appreciated! Thank you so much for your time!

Best regards,
Sherin

**Comment by yihming** [comment] 2024-09-01 16:58
Hi @SXerin ,

You may try v2.4.1 instead of v2.6.3 of cellranger workflow. 

The issue is that we've updated our workflow to work with stratocumulus (a tool we use for file sync between cloud and VM machine) latest version, which drops `--backend` option. However, since we no longer have access to `gcr.io/broad-cumulus`, the mkfastq docker image there was not updated.

To solve your issue, I suggest either of the following two options:

1. You may try v2.4.1 of cellranger workflow for your mkfastq step, i.e. set `run_count` to `false`. Then starting from the FASTQ files generated, submit another cellranger job with `run_mkfastq` set to `false` and with cellranger workflow v2.6.3.
2. If you are associated with Broad Institute, then you may try their internal bclconverter workflow for the mkfastq step, and then use our cellranger workflow for the count step. You may reach out to [Deeptha Srirangam](mailto:dsrirang@broadinstitute.org) for more details.

Hope it helps.

**Comment by yihming** [comment] 2024-09-10 20:25
I'll close this thread. Please feel free to open it if your issue persists.

**Closed by yihming** 2024-09-10 20:25 UTC

**Comment by SXerin** [comment] 2024-09-12 19:27
Hi Yiming,

Thank you for the guidance and I am very sorry for the late response.

I’ve used CellRanger 7.2.0 instead of 7.1.0 and was able to generate fastq files with cumulus v2.6.3.

Using cumulus v2.4.1 and cellranger 7.1.0 will result in the same error.

Thanks again!
Sherin

From: Yiming Yang ***@***.***>
Date: Sunday, September 1, 2024 at 12:59 PM
To: lilab-bcb/cumulus ***@***.***>
Cc: Simayijiang Xirenayi ***@***.***>, Mention ***@***.***>
Subject: Re: [lilab-bcb/cumulus] Terra CellRanger Workflow | run_cellranger_mkfastq: strato sync: error: the following arguments are required: --backend (Issue #419)

Hi @SXerin<https://github.com/SXerin> ,

You may try v2.4.1 instead of v2.6.3 of cellranger workflow.

The issue is that we've updated our workflow to work with stratocumulus (a tool we use for file sync between cloud and VM machine) latest version, which drops --backend option. However, since we no longer have access to gcr.io/broad-cumulus, the mkfastq docker image there was not updated.

To solve your issue, I suggest either of the following two options:

  1.  You may try v2.4.1 of cellranger workflow for your mkfastq step, i.e. set run_count to false. Then starting from the FASTQ files generated, submit another cellranger job with run_mkfastq set to false and with cellranger workflow v2.6.3.
  2.  If you are associated with Broad Institute, then you may try their internal bclconverter workflow for the mkfastq step, and then use our cellranger workflow for the count step. You may reach out to Deeptha ***@***.***> for more details.

Hope it helps.

Sincerely,
Yiming
